apiVersion: v1
kind: Service
metadata:
  name: lidar-api-service
  labels:
    app: lidar-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: lidar-api