apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidar-local-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /Volumes/fts-addlidar
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidar-data-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidar-ouputput-local-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-output-storage
  hostPath:
    path: /Users/pierreguilbert/Works/git/github/EPFL-ENAC/AddLidar-API/lidar-api/output
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidar-data-output-pvc
spec:
  storageClassName: local-output-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
