services:
  lidar-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - PORT=80
      - ENV=development
    volumes:
      - ./data:/data

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lidar_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: