# https://github.com/EPFL-ENAC/epfl-enac-build-push-deploy-action#readme
name: deploy

"on":
  push:
    branches:
      - dev
    tags: ["v*.*.*"]

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: EPFL-ENAC/epfl-enac-build-push-deploy-action/.github/workflows/deploy.yml@v2.4.0
    secrets:
      token: ${{ secrets.CD_TOKEN }}
    with:
      # Optional inputs can be passed here
      ORG: epfl-eso #.e.g epfl-cryos
      REPO: addlidar # ex. lgb-trsc
      build_context: '["./backend/lidar-api", "./frontend", "./compression", "./scanner", "./potree-converter"]'
